Form/Type/PortfolioType.php
<?php

namespace Icap\PortfolioBundle\Form\Type;

use JMS\DiExtraBundle\Annotation as DI;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @DI\FormType
 */
class PortfolioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('commentsViewAt', 'datetime', array(
                    'widget' => 'single_text'
                ))
            ->add('comments', 'text', array('mapped' => false))
            ->add('widgets', 'text', array('mapped' => false))
            ->add('title', 'text');
    }

    public function getName()
    {
        return 'icap_portfolio_portfolio_form';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class'         => 'Icap\PortfolioBundle\Entity\Portfolio',
                'translation_domain' => 'icap_portfolio',
                'csrf_protection'    => false,
                'date_format'        => DateTimeType::HTML5_FORMAT
            )
        );
    }
}

Resources/views/export/leap2a/badges.leap2a.twig
    <entry>
        <title>{{ widget.label }}</title>
        <id>portfolio:badges/{{ widget.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content></content>
        <rdf:type rdf:resource="leap2:selection"/>
        <category term="Grouping" scheme="categories:selection_type#"/>
{% for badgesWidgetBadge in widget.badges %}
        <link rel="leap2:has_part" href="portfolio:badge/{{ badgesWidgetBadge.id }}" leap2:display_order="{{ loop.index }}"/>
{% endfor %}
    </entry>
{% for badgesWidgetBadge in widget.badges %}
    <entry>
        <title>{{ badgesWidgetBadge.badge.name }}</title>
        <id>portfolio:badge/{{ badgesWidgetBadge.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content type="html">{{ badgesWidgetBadge.badge.description }}</content>
        <rdf:type rdf:resource="leap2:achievement"/>
        <link rel="leap2:is_part_of" href="portfolio:badges/{{ widget.id }}" leap2:display_order="{{ loop.index }}"/>
    </entry>
{% endfor %}

Resources/views/export/leap2a/experience.leap2a.twig
    <entry>
        <title>{{ widget.label }}</title>
        <id>portfolio:experience/{{ widget.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content type="html"><![CDATA[{{ widget.description|raw }}]]></content>
        <leap2:orgdata leap2:field="website">{{ widget.website }}</leap2:orgdata>
        <leap2:orgdata leap2:field="legal_org_name">{{ widget.companyname }}</leap2:orgdata>
        <leap2:myrole>{{ widget.post }}</leap2:myrole>
        <leap2:date leap2:point="start">{{ widget.startDate|date(constant('\DateTime::ATOM')) }}</leap2:date>
        <leap2:date leap2:point="end">{{ widget.endDate|date(constant('\DateTime::ATOM')) }}</leap2:date>
        <rdf:type rdf:resource="leap2:activity"/>
        <category term="Work" scheme="categories:life_area"/>
    </entry>

Resources/views/export/leap2a/formations.leap2a.twig
    <entry>
        <title>{{ widget.label }}</title>
        <id>portfolio:formations/{{ widget.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content type="text">{{ widget.name }}</content>
        <leap2:date leap2:point="start">{{ widget.startDate|date(constant('\DateTime::ATOM')) }}</leap2:date>
        <leap2:date leap2:point="end">{{ widget.endDate|date(constant('\DateTime::ATOM')) }}</leap2:date>
        <rdf:type rdf:resource="leap2:activity"/>
        <category term="Education" scheme="categories:life_area"/>
{% for formationWidgetResource in widget.resources %}
    {% set formationWidgetResourceId = (formationWidgetResource.uri is not null) ? formationWidgetResource.id : formationWidgetResource.resource.id %}
    <link rel="leap2:has_part" href="portfolio:resource/{{ formationWidgetResourceId }}" leap2:display_order="{{ loop.index }}"/>
{% endfor %}
    </entry>
{% for formationWidgetResource in widget.resources %}
{% set formationWidgetResourceId = (formationWidgetResource.uri is not null) ? formationWidgetResource.id : formationWidgetResource.resource.id %}
{% set formationWidgetResourceTitle = (formationWidgetResource.uri is not null) ? formationWidgetResource.uriLabel : formationWidgetResource.resource.name %}
{% set formationWidgetResourceUri = (formationWidgetResource.uri is not null) ? formationWidgetResource.uri : url("claro_resource_open", {'node': formationWidgetResource.resource.id, 'resourceType': formationWidgetResource.resource.resourceType.name }) %}
{% set formationWidgetResourceUpdatedAt = (formationWidgetResource.uri is not null) ? widget.updatedAt : formationWidgetResource.resource.modificationDate %}
    <entry>
        <title>{{ formationWidgetResourceTitle }}</title>
        <id>portfolio:resource/{{ formationWidgetResourceId }}</id>
        <updated>{{ formationWidgetResourceUpdatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content></content>
        <rdf:type rdf:resource="leap2:resource"/>
        <category term="Web" scheme="categories:resource_type#"/>
        <link rel="self" href="{{ formationWidgetResourceUri }}" />
        <link rel="leap2:is_part_of" href="portfolio:formations/{{ widget.id }}" leap2:display_order="{{ loop.index }}"/>
    </entry>
{% endfor %}

Resources/views/export/leap2a/skills.leap2a.twig
    <entry>
        <title>{{ widget.label }}</title>
        <id>portfolio:skills/{{ widget.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content></content>
        <rdf:type rdf:resource="leap2:selection"/>
        <category term="Abilities" scheme="categories:selection_type#"/>
{% for skillsWidgetSkill in widget.skills %}
        <link rel="leap2:has_part" href="portfolio:skill/{{ skillsWidgetSkill.id }}" leap2:display_order="{{ loop.index }}"/>
{% endfor %}
    </entry>
{% for skillsWidgetSkill in widget.skills %}
    <entry>
        <title>{{ skillsWidgetSkill.name }}</title>
        <id>portfolio:skill/{{ skillsWidgetSkill.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content></content>
        <rdf:type rdf:resource="leap2:ability"/>
        <link rel="leap2:is_part_of" href="portfolio:skills/{{ widget.id }}" leap2:display_order="{{ loop.index }}"/>
    </entry>
{% endfor %}

Resources/views/export/leap2a/text.leap2a.twig
    <entry>
        <title>{{ widget.label }}</title>
        <id>portfolio:text/{{ widget.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content type="html"><![CDATA[{{ widget.text|raw }}]]></content>
        <rdf:type rdf:resource="leap2:entry"/>
    </entry>

Resources/views/export/leap2a/userInformation.leap2a.twig
    <entry>
        <title>{{ widget.label }}</title>
        <id>portfolio:text/{{ widget.id }}</id>
        <updated>{{ widget.updatedAt|date(constant('\DateTime::ATOM')) }}</updated>
        <content></content>
        <rdf:type rdf:resource="leap2:person"/>
        <leap2:persondata leap2:field="dob">{{ widget.birthDate|date(constant('\DateTime::ATOM')) }}</leap2:persondata>
        <leap2:persondata leap2:field="other" leap2:label="city">{{ widget.city }}</leap2:persondata>
    </entry>